import streamlit as st
import pandas as pd
import plotly.express as px
import joblib

st.set_page_config(page_title="Video Game Sales Predictor", layout="wide")

try:
    model = joblib.load('vgsales_model.pkl')
except FileNotFoundError:
    st.error("Model file 'vgsales_model.pkl' not found. Please run 'train_model.py' first.")
    st.stop()

try:
    data = pd.read_csv("vgsales.csv").dropna()
except FileNotFoundError:
    st.error("Data file 'vgsales.csv' not found.")
    st.stop()

st.markdown("""
<style>
    .main { background-color: #0E1117; }
    h1 { color: #87CEEB; font-family: 'Helvetica Neue', sans-serif; text-align: center; }
    h2 { color: #FAFAFA; font-weight: 300; }
    p { font-size: 1.1rem; color: #B0B3B8; }
    .stMetric { background-color: #262730; padding: 15px; border-radius: 10px; }
    .stSlider label { color: white; }
</style>
""", unsafe_allow_html=True)

st.title("🎮 Global Video Game Sales Prediction")
st.markdown("---")

with st.sidebar:
    st.header("Input Sales Data (in Millions)")
    
    rank = st.number_input('Rank (Lower is Better)', min_value=1, max_value=data['Rank'].max(), value=100)
    na_sales = st.slider('North America Sales (NA_Sales)', 0.0, float(data['NA_Sales'].max()), 0.5)
    eu_sales = st.slider('Europe Sales (EU_Sales)', 0.0, float(data['EU_Sales'].max()), 0.25)
    jp_sales = st.slider('Japan Sales (JP_Sales)', 0.0, float(data['JP_Sales'].max()), 0.1)
    other_sales = st.slider('Other Regions Sales (Other_Sales)', 0.0, float(data['Other_Sales'].max()), 0.05)

input_data = pd.DataFrame([[rank, na_sales, eu_sales, jp_sales, other_sales]], 
                          columns=["Rank", "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"])

prediction = model.predict(input_data)[0]

col_pred, col_viz = st.columns([1, 2])

with col_pred:
    st.subheader("Predicted Global Sales")
    st.metric(label="Estimated Global Sales (in Millions)", value=f"{prediction:.2f}M")
    
    st.subheader("Input Summary")
    st.dataframe(input_data, hide_index=True)

with col_viz:
    st.header("Sales Distribution Analysis")
    
    st.subheader("Sales by Genre")
    st.write("This pie chart shows the market share of the top-selling game genres by total sales volume, highlighting which categories dominate the industry.")
    
    genre_sales = data.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).head(10)
    fig_genre = px.pie(names=genre_sales.index, values=genre_sales.values,
                       hole=0.4, title="", color_discrete_sequence=px.colors.qualitative.Pastel)
    st.plotly_chart(fig_genre, use_container_width=True)

    st.subheader("Top Publishers")
    st.write("The bar chart visualizes the global sales generated by the top 10 publishers, demonstrating their market power.")
    
    publisher_sales = data.groupby("Publisher")["Global_Sales"].sum().nlargest(10).sort_values(ascending=True)
    fig_pub = px.bar(x=publisher_sales.values, y=publisher_sales.index, orientation='h',
                     color=publisher_sales.values, color_continuous_scale='Plasma', title="")
    fig_pub.update_layout(xaxis_title="Global Sales (Millions)", yaxis_title="")
    st.plotly_chart(fig_pub, use_container_width=True)